/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'demo': RouteRecordInfo<'demo', '/demo', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'PlanCache': RouteRecordInfo<'PlanCache', '/plan', Record<never, never>, Record<never, never>>,
    'PlanInfo': RouteRecordInfo<'PlanInfo', '/plan/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/plan/plan-recipe-card-list/': RouteRecordInfo<'/plan/plan-recipe-card-list/', '/plan/plan-recipe-card-list', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/self-content-tab/': RouteRecordInfo<'/profile/self-content-tab/', '/profile/self-content-tab', Record<never, never>, Record<never, never>>,
    'Recipe': RouteRecordInfo<'Recipe', '/recipe', Record<never, never>, Record<never, never>>,
    'RecipeInfo': RouteRecordInfo<'RecipeInfo', '/recipe/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'RecipeAdd': RouteRecordInfo<'RecipeAdd', '/recipe/add', Record<never, never>, Record<never, never>>,
    '/recipe/tab-pages/food-category/': RouteRecordInfo<'/recipe/tab-pages/food-category/', '/recipe/tab-pages/food-category', Record<never, never>, Record<never, never>>,
    'RecipeListFoodCategory': RouteRecordInfo<'RecipeListFoodCategory', '/recipe/tab-pages/food-category/:categoryId', { categoryId: ParamValue<true> }, { categoryId: ParamValue<false> }>,
    '/recipe/tab-pages/recipe-category/': RouteRecordInfo<'/recipe/tab-pages/recipe-category/', '/recipe/tab-pages/recipe-category', Record<never, never>, Record<never, never>>,
    'RecipeListCategory': RouteRecordInfo<'RecipeListCategory', '/recipe/tab-pages/recipe-category/:categoryId', { categoryId: ParamValue<true> }, { categoryId: ParamValue<false> }>,
    '/recipe/tab-pages/RecipeSelf': RouteRecordInfo<'/recipe/tab-pages/RecipeSelf', '/recipe/tab-pages/RecipeSelf', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'ScrollCache': RouteRecordInfo<'ScrollCache', '/scroll-cache', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
