/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<'Home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'chat': RouteRecordInfo<'chat', '/chat', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'demo': RouteRecordInfo<'demo', '/demo', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'message': RouteRecordInfo<'message', '/message', Record<never, never>, Record<never, never>>,
    'MessageComment': RouteRecordInfo<'MessageComment', '/message/comment', Record<never, never>, Record<never, never>>,
    'MessageReply': RouteRecordInfo<'MessageReply', '/message/reply', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'Plan': RouteRecordInfo<'Plan', '/plan', Record<never, never>, Record<never, never>>,
    'PlanInfo': RouteRecordInfo<'PlanInfo', '/plan/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'Profile': RouteRecordInfo<'Profile', '/profile', Record<never, never>, Record<never, never>>,
    'ProfileEdit': RouteRecordInfo<'ProfileEdit', '/profile/edit', Record<never, never>, Record<never, never>>,
    '/profile/edit/mobile-edit-popup/': RouteRecordInfo<'/profile/edit/mobile-edit-popup/', '/profile/edit/mobile-edit-popup', Record<never, never>, Record<never, never>>,
    '/profile/edit/password-edit-popup/': RouteRecordInfo<'/profile/edit/password-edit-popup/', '/profile/edit/password-edit-popup', Record<never, never>, Record<never, never>>,
    '/profile/self-content-tab/': RouteRecordInfo<'/profile/self-content-tab/', '/profile/self-content-tab', Record<never, never>, Record<never, never>>,
    '/profile/self-content-tab/recipe-menu-tab': RouteRecordInfo<'/profile/self-content-tab/recipe-menu-tab', '/profile/self-content-tab/recipe-menu-tab', Record<never, never>, Record<never, never>>,
    '/profile/self-content-tab/user-collect-tab/': RouteRecordInfo<'/profile/self-content-tab/user-collect-tab/', '/profile/self-content-tab/user-collect-tab', Record<never, never>, Record<never, never>>,
    'Recipe': RouteRecordInfo<'Recipe', '/recipe', Record<never, never>, Record<never, never>>,
    'RecipeInfo': RouteRecordInfo<'RecipeInfo', '/recipe/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/recipe/action-func-bar/': RouteRecordInfo<'/recipe/action-func-bar/', '/recipe/action-func-bar', Record<never, never>, Record<never, never>>,
    '/recipe/action-func-bar/func-icon/add-to-menu': RouteRecordInfo<'/recipe/action-func-bar/func-icon/add-to-menu', '/recipe/action-func-bar/func-icon/add-to-menu', Record<never, never>, Record<never, never>>,
    '/recipe/action-func-bar/func-icon/add-to-plan': RouteRecordInfo<'/recipe/action-func-bar/func-icon/add-to-plan', '/recipe/action-func-bar/func-icon/add-to-plan', Record<never, never>, Record<never, never>>,
    '/recipe/action-func-bar/func-icon/collect': RouteRecordInfo<'/recipe/action-func-bar/func-icon/collect', '/recipe/action-func-bar/func-icon/collect', Record<never, never>, Record<never, never>>,
    '/recipe/action-func-bar/func-icon/comment': RouteRecordInfo<'/recipe/action-func-bar/func-icon/comment', '/recipe/action-func-bar/func-icon/comment', Record<never, never>, Record<never, never>>,
    '/recipe/action-func-bar/func-icon/share': RouteRecordInfo<'/recipe/action-func-bar/func-icon/share', '/recipe/action-func-bar/func-icon/share', Record<never, never>, Record<never, never>>,
    'RecipeForm': RouteRecordInfo<'RecipeForm', '/recipe/form', Record<never, never>, Record<never, never>>,
    '/recipe/more-popup/': RouteRecordInfo<'/recipe/more-popup/', '/recipe/more-popup', Record<never, never>, Record<never, never>>,
    '/recipe/recipe-comment/': RouteRecordInfo<'/recipe/recipe-comment/', '/recipe/recipe-comment', Record<never, never>, Record<never, never>>,
    '/recipe/tab-pages/food-category/': RouteRecordInfo<'/recipe/tab-pages/food-category/', '/recipe/tab-pages/food-category', Record<never, never>, Record<never, never>>,
    'RecipeListFoodCategory': RouteRecordInfo<'RecipeListFoodCategory', '/recipe/tab-pages/food-category/:categoryId', { categoryId: ParamValue<true> }, { categoryId: ParamValue<false> }>,
    '/recipe/tab-pages/recipe-category/': RouteRecordInfo<'/recipe/tab-pages/recipe-category/', '/recipe/tab-pages/recipe-category', Record<never, never>, Record<never, never>>,
    'RecipeListCategory': RouteRecordInfo<'RecipeListCategory', '/recipe/tab-pages/recipe-category/:categoryId', { categoryId: ParamValue<true> }, { categoryId: ParamValue<false> }>,
    '/recipe/tab-pages/RecipeSelf': RouteRecordInfo<'/recipe/tab-pages/RecipeSelf', '/recipe/tab-pages/RecipeSelf', Record<never, never>, Record<never, never>>,
    'RecipeMenuInfo': RouteRecordInfo<'RecipeMenuInfo', '/recipe-menu/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'RecipeMenuForm': RouteRecordInfo<'RecipeMenuForm', '/recipe-menu/form', Record<never, never>, Record<never, never>>,
    '/recipe-menu/more-popup/': RouteRecordInfo<'/recipe-menu/more-popup/', '/recipe-menu/more-popup', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'ScrollCache': RouteRecordInfo<'ScrollCache', '/scroll-cache', Record<never, never>, Record<never, never>>,
    'Search': RouteRecordInfo<'Search', '/search', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'SmsCodeLogin': RouteRecordInfo<'SmsCodeLogin', '/sms-code-login', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
    'UserCollectInfo': RouteRecordInfo<'UserCollectInfo', '/user-collect/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'UserCollectForm': RouteRecordInfo<'UserCollectForm', '/user-collect/form', Record<never, never>, Record<never, never>>,
    '/user-collect/more-popup/': RouteRecordInfo<'/user-collect/more-popup/', '/user-collect/more-popup', Record<never, never>, Record<never, never>>,
  }
}
